In [15]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
movies = pd.read_csv('imdb_top_1000.csv')

In [7]:
movies.head(1)

Movie_id                                        Poster_Link  \
0         0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   

               Series_Title Released_Year Certificate  Runtime  Genre  \
0  The Shawshank Redemption          1994           A  142 min  Drama   

   IMDB_Rating                                           Overview  Meta_score  \
0          9.3  Two imprisoned men bond over a number of years...        80.0   

         Director        Star1           Star2       Star3           Star4  \
0  Frank Darabont  Tim Robbins  Morgan Freeman  Bob Gunton  William Sadler   

                                              Actors  No_of_Votes       Gross  
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...      2343110  28,341,469

In [10]:
#Get a count of the number of row/movies in the data set and the number of columns
movies.shape

(1000, 18)

In [16]:
#Create a list of important columns for the recommendation engine
columns = ['Actors', 'Director', 'Genre', 'Series_Title']

In [17]:
#Check for any missing values in the important columns
movies[columns].isnull().values.any()

False

In [18]:
#Create a function to combine the values of the important columns into a single string
def get_important_features(data):
  important_features = []
  for i in range(0, data.shape[0]):
    important_features.append(data['Actors'][i] + ' ' + data['Director'][i] + ' ' + data['Genre'][i] + ' ' + data['Series_Title'][i])

  return important_features

In [19]:
#Create a column to hold the combined strings
movies['important_features'] = get_important_features(movies)

#Show the data
movies.head(3)

Movie_id                                        Poster_Link  \
0         0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1         1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2         2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4                                             Actors  \
0  William Sadler  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1    Diane Keaton  Marlon Brando, Al Pacino, James Caan, Diane Ke...   
2   Michael Caine  Christian Bale, Heath Ledger, Aaron Eckhart, M...   

   No_of_Votes        Gross                                 important_features  
0      2343110   28,341,469  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...  
1      1620367  134,966,411  Marlon Brando, Al Pacino, James Caan, Diane Ke...  
2      2303232  534,858,444  Christian Bale, Heath Ledger, Aaron Eckhart, M...

In [21]:
#Convert the text to a matrix of token counts
cm = CountVectorizer().fit_transform(movies['important_features'])

In [23]:
#Get the cosine similarity matrix fromt he count matrix
cs = cosine_similarity(cm)
#Print the cosine similarity matrx
print(cs)

[[1.         0.13801311 0.13363062 ... 0.06482037 0.14824986 0.06681531]
 [0.13801311 1.         0.19364917 ... 0.06262243 0.07161149 0.12909944]
 [0.13363062 0.19364917 1.         ... 0.06063391 0.06933752 0.125     ]
 ...
 [0.06482037 0.06262243 0.06063391 ... 1.         0.13453456 0.        ]
 [0.14824986 0.07161149 0.06933752 ... 0.13453456 1.         0.13867505]
 [0.06681531 0.12909944 0.125      ... 0.         0.13867505 1.        ]]


In [24]:
#Get the shape of the cosine similarity matrix
cs.shape

(1000, 1000)

In [27]:
#Get the title of the movie that the user likes
def recommend(title):
    #Find the movie id
    movie_id = movies[movies.Series_Title == title]['Movie_id'].values[0]
    #Create a list of enumerations for the similarity score
    scores = list(enumerate(cs[movie_id]))
    #Sort the list
    sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
    sorted_scores = sorted_scores[1:]
    #Create a loop to print the first 7 similar movies
    j= 0
    print('The 7 most recommended movies', title, 'are:\n')
    for item in sorted_scores:
        movie_title = movies[movies.Movie_id == item[0]]['Series_Title'].values[0]
        print(j+1, movie_title)
        j = j + 1
        if j > 6:
            break

In [28]:
recommend('Pulp Fiction')

The 7 most recommended movies Pulp Fiction are:

1 Kill Bill: Vol. 1
2 The Hateful Eight
3 Kill Bill: Vol. 2
4 Die Hard: With a Vengeance
5 Reservoir Dogs
6 Enter the Dragon
7 Stagecoach


In [32]:
new_movies = movies[['Movie_id', 'Series_Title', 'Overview']]

In [33]:
new_movies.head()

Movie_id              Series_Title  \
0         0  The Shawshank Redemption   
1         1             The Godfather   
2         2           The Dark Knight   
3         3    The Godfather: Part II   
4         4              12 Angry Men   

                                            Overview  
0  Two imprisoned men bond over a number of years...  
1  An organized crime dynasty's aging patriarch t...  
2  When the menace known as the Joker wreaks havo...  
3  The early life and career of Vito Corleone in ...  
4  A jury holdout attempts to prevent a miscarria...

In [29]:
import pickle

In [39]:
pickle.dump(new_movies.to_dict(), open('movies.pkl', 'wb'))

In [38]:
new_movies['Series_Title'].values

array(['The Shawshank Redemption', 'The Godfather', 'The Dark Knight',
       'The Godfather: Part II', '12 Angry Men',
       'The Lord of the Rings: The Return of the King', 'Pulp Fiction',
       "Schindler's List", 'Inception', 'Fight Club',
       'The Lord of the Rings: The Fellowship of the Ring',
       'Forrest Gump', 'Il buono, il brutto, il cattivo',
       'The Lord of the Rings: The Two Towers', 'The Matrix',
       'Goodfellas', 'Star Wars: Episode V - The Empire Strikes Back',
       "One Flew Over the Cuckoo's Nest", 'Hamilton', 'Gisaengchung',
       'Soorarai Pottru', 'Interstellar', 'Cidade de Deus',
       'Sen to Chihiro no kamikakushi', 'Saving Private Ryan',
       'The Green Mile', 'La vita è bella', 'Se7en',
       'The Silence of the Lambs', 'Star Wars', 'Seppuku',
       'Shichinin no samurai', "It's a Wonderful Life", 'Joker',
       'Whiplash', 'The Intouchables', 'The Prestige', 'The Departed',
       'The Pianist', 'Gladiator', 'American History X',
     

In [ ]:
pickle.dump(similarity)